version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: "engov_build"
    dir: ./apps/cli/
    binary: engov
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
